# Camera icon for website
baseurl: https://www.lyeutsaon.com/

# Default post title
default_post_title: Halo

#Date Format
date_format: MM/DD/YYYY

# Comment.
comments:
  # Disqus comment
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Register service worker
service_worker: false

# Local search with atom.xml, dependency hexo-generator-feed plugin
local_search: true

# using viewer.js to view image
# https://fengyuanchen.github.io/viewerjs/
image_viewer: false

# Table of content
# Maybe support more toc style in future.
toc:
  enable: false

home: /blog/
archives: /blog/archives
about: /blog/about
tags: /blog/tags            

author: Zhuang Liu